### ISSUE TITLE
Switch to Api v2

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/now-pipeline#33]
https://zeit.co/blog/api-2

Because old API is not working anymore

**Comment by baires** [comment]
Same here, my pipeline is broken

```
TypeError: Cannot read property 'data' of undefined

    at now.createDeployment.then.catch.r (/usr/src/node_modules/now-pipeline/src/index.js:170:36)

    at <anonymous>

    at process._tickCallback (internal/process/next_tick.js:188:7)

script returned exit code 255
```
